---
title: "dummy_data"
author: "AnMei Chen"
date: "1/15/2022"
output: html_document
---

```{r}
library(tidyverse)
library(fastDummies)
```

```{r}
old_le_df =
  read_csv("./data/Complete_Data.CSV") %>% 
  rename("HDI" = "incomecompositionofresources", "percent_exp" = "percentageexpenditure", "total_exp" = "totalexpenditure", "le" = "lifeexpectancy", "adult_mort" = "adult_mortality", "thin_1_19" = "thinness1_19years", "thin_5_9" = "thinness5_9years", "under_five" = "under_fivedeaths")

summary(old_le_df)
```



```{r}
new_le_df =
  read_csv("./data/Complete_Data.CSV") %>% 
  rename("HDI" = "incomecompositionofresources", "percent_exp" = "percentageexpenditure", "total_exp" = "totalexpenditure", "le" = "lifeexpectancy", "adult_mort" = "adult_mortality", "thin_1_19" = "thinness1_19years", "thin_5_9" = "thinness5_9years", "under_five" = "under_fivedeaths") %>% 
  mutate(
    polio = ifelse(polio < 78, "low", ifelse(polio > 78 & polio < 82.41, "median", "high")),
    hepatitis_b = ifelse(hepatitis_b < 71, "low", ifelse(hepatitis_b > 71 & hepatitis_b < 77.93, "median", "high")),
    diphtheria = ifelse(diphtheria < 78, "low", ifelse(diphtheria > 78 & diphtheria < 82.15, "median", "high"))
  )
```

## dummy variables

```{r}
dum_le_df =
  new_le_df %>% 
  dummy_cols(select_columns = c("status","polio","hepatitis_b","diphtheria"),remove_selected_columns = TRUE)

write.csv(dum_le_df,"./data/Dummy_Data.CSV", row.names = FALSE)
```

