---
title: "Merge Data"
output: html_document
---

```{r}
library(tidyverse)
library(mice)
```


```{r}
life_expectancy = 
  read_csv("data/life_expectancy.csv") %>% 
  janitor::clean_names() %>% 
  mutate(country = recode(country,
      "AntiguaandBarbuda" = "Antigua and Barbuda",
      "Bolivia(PlurinationalStateof)" = "Bolivia (Plurinational State of)", 
      "BosniaandHerzegovina" = "Bosnia and Herzegovina",
      "BruneiDarussalam" = "Brunei Darussalam",
      "BurkinaFaso" = "Burkina Faso",
      "CostaRica" = "Costa Rica",
      "Coted'Ivoire" = "Cote d'Ivoire",
      "CaboVerde" = "Cabo Verde",
      "CentralAfricanRepublic" = "Central African Republic",
      "CookIslands" = "Cook Islands",
      "Czechia" = "Czech Republic",
      "DemocraticPeople'sRepublicofKorea" = "Korea (Democratic People's Republic of)",
      "DemocraticRepublicoftheCongo" = "Congo (Democratic Republic of the)",
      "DominicanRepublic" = "Dominican Republic",
      "ElSalvador" = "El Salvador",
      "EquatorialGuinea" = "Equatorial Guinea",
      "Iran(IslamicRepublicof)" = "Iran (Islamic Republic of)",
      "LaoPeople'sDemocraticRepublic" = "Lao People's Democratic Republic",
      "MarshallIslands" = "Marshall Islands",
      "Micronesia(FederatedStatesof)" = "Micronesia (Federated States of)",
      "NewZealand" = "New Zealand",
      "PapuaNewGuinea" = "Papua New Guinea",
      "RepublicofKorea" = "Korea (Republic of)",
      "RepublicofMoldova" = "Moldova (Republic of)",
      "RussianFederation" = "Russian Federation",
      "SaintKittsandNevis" = "Saint Kitts and Nevis",
      "SaintLucia" = "Saint Lucia",
      "SaintVincentandtheGrenadines" = "Saint Vincent and the Grenadines",
      "SanMarino" = "San Marino",
      "SaoTomeandPrincipe" = "Sao Tome and Principe",
      "SaudiArabia" = "Saudi Arabia",
      "SierraLeone" = "Sierra Leone",
      "SolomonIslands" = "Solomon Islands",
      "SouthAfrica" = "South Africa",
      "SouthSudan" = "South Sudan",
      "SriLanka" = "Sri Lanka",
      "SyrianArabRepublic" = "Syrian Arab Republic",
      "TheformerYugoslavrepublicofMacedonia" = "Macedonia (the former Yugoslav Republic of)",
      "TrinidadandTobago" = "Trinidad and Tobago",
      "UnitedArabEmirates" = "United Arab Emirates",
      "UnitedKingdomofGreatBritainandNorthernIreland" = "United Kingdom of Great Britain and Northern Ireland",
      "UnitedRepublicofTanzania" = "Tanzania, United Republic of",
      "UnitedStatesofAmerica" = "United States of America",
      "Venezuela(BolivarianRepublicof)" = "Venezuela (Bolivarian Republic of)",
      "VietNam" = "Viet Nam")) 

continent_df =
  read_csv("data/countryContinent.csv") %>%
  janitor::clean_names() %>% 
  select(country,continent) 

# df with continent

life_expectancy_df = 
  life_expectancy %>% 
  left_join(continent_df, by = "country") %>% 
  relocate(country,continent) %>% 
  mutate(year = as.character(year)) 

```


```{r}
check_na = function(x) {
  
  na = 
    life_expectancy_df %>%  
    filter(is.na(x)) %>%  
    count()
  
  return(na)
}

## Check for NA values 
colSums(is.na(life_expectancy_df))

tempData <- mice(life_expectancy_df,m=5,maxit=50,meth='cart',seed=100)
Complete_df <- complete(tempData,1)

colSums(is.na(Complete_df))

write.csv(Complete_df, file = ".\\data/Complete_Data", row.names = F)


```

