---
title: "stepwise_model"
author: "AnMei Chen"
date: "1/5/2022"
output: html_document
---

```{r}
library(tidyverse)
library(MASS)
library(corrplot)
library(performance) # vif
library(caret)
library(car)
library(Metrics)
```


```{r}
le_df = 
  read_csv("./data/Complete_Data.CSV") %>% 
  rename("HDI" = "incomecompositionofresources", "percent_exp" = "percentageexpenditure", "total_exp" = "totalexpenditure", "le" = "lifeexpectancy", "adult_mort" = "adult_mortality", "thin_1_19" = "thinness1_19years", "thin_5_9" = "thinness5_9years", "under_five" = "under_fivedeaths")
```

# Correlation Matrix
```{r}
le_df =
  le_df %>%
  dplyr::select(-c(country,continent,year,status))

corrplot(cor(le_df), type = "upper", diag = FALSE, method = "square", addCoef.col = "black", number.cex = .5, tl.col = "black", tl.cex = .9)
```

## Stepwise by AIC 
```{r}
le_df = 
  read_csv("./data/Complete_Data.CSV") %>% 
  rename("HDI" = "incomecompositionofresources", "percent_exp" = "percentageexpenditure", "total_exp" = "totalexpenditure", "le" = "lifeexpectancy", "adult_mort" = "adult_mortality", "thin_1_19" = "thinness1_19years", "thin_5_9" = "thinness5_9years", "under_five" = "under_fivedeaths")

full_model =
  lm(le ~ adult_mort + infantdeaths + alcohol + percent_exp + hepatitis_b + measles + bmi + under_five + polio + total_exp + diphtheria + hiv_aids + gdp + population + thin_1_19 + thin_5_9 + HDI + schooling, data = le_df)

step_model = stepAIC(full_model, direction = "both", 
                      trace = FALSE)
summary(step_model)
```

## Use diagnostic plots to check stepwise model

```{r}
stepwise = lm(le ~ adult_mort + infantdeaths + alcohol + bmi + 
    under_five + polio + total_exp + diphtheria + hiv_aids + 
    gdp + thin_1_19 + HDI + schooling, data = le_df)

par(mfrow = c(2, 2))
par(mar = c(2,2,2,2))
#Residuals vs Fitted values Plot
plot(stepwise, which = 1)
# QQ Plot
plot(stepwise, which = 2)
# Scale-location plot
plot(stepwise, which = 3)
# Residuals vs. Leverage
plot(stepwise, which = 5)
par(mfrow = c(1, 1)) 
par(mar = c(3,3,3,3))

```

## Box-cox Transformation
```{r}
bc = boxcox(stepwise)
lambda = bc$x[which.max(bc$y)]
lambda

le_df =
  le_df %>% 
  mutate(bc_le = (le)^1.5)

stepwise_bc = lm(bc_le ~ adult_mort + infantdeaths + alcohol + bmi + under_five + polio + total_exp + diphtheria + hiv_aids + 
    gdp + thin_1_19 + HDI + schooling, data = le_df)
summary(stepwise_bc)

stepwise = lm(le ~ adult_mort + infantdeaths + alcohol + bmi + 
    under_five + polio + total_exp + diphtheria + hiv_aids + 
    gdp + thin_1_19 + HDI + schooling, data = le_df)
summary(stepwise)

par(mfrow = c(2, 1))
par(mar = c(2,2,2,2))

plot(stepwise_bc, which = 1)  
plot(stepwise, which = 1)

plot(stepwise_bc, which = 2)  
plot(stepwise, which = 2)

plot(stepwise_bc, which = 3)  
plot(stepwise, which = 3)

plot(stepwise_bc, which = 5)  
plot(stepwise, which = 5)

par(mfrow = c(1, 1)) 
par(mar = c(3,3,3,3))
```

## Identify influentical observations

```{r}
plot(stepwise, which = 5)

# Identify influential observations using Cook's distance
cutoff <- 4/nrow(le_df)
plot(stepwise, which = 4, cook.levels = cutoff)
abline(h = cutoff, lty = 2, col = "red")

cook = cooks.distance(stepwise)
influential_obs = as.numeric(names(cook)[(cook > cutoff)])

#define new data frame with influential points removed
no_influ_le = le_df[-influential_obs, ]

no_influ_stepwise = lm(le ~ adult_mort + infantdeaths + alcohol + bmi + under_five + polio + total_exp + diphtheria + hiv_aids + gdp + thin_1_19 + HDI + schooling, data = no_influ_le)
summary(no_influ_stepwise)
```

## Leverage checking 

```{r}
# compare models with and without influential observations
no_influ_stepwise = lm(le ~ adult_mort + infantdeaths + alcohol + bmi + under_five + polio + total_exp + diphtheria + hiv_aids + gdp + thin_1_19 + HDI + schooling, data = no_influ_le)
summary(no_influ_stepwise)

stepwise = lm(le ~ adult_mort + infantdeaths + alcohol + bmi + under_five + polio + total_exp + diphtheria + hiv_aids + gdp + thin_1_19 + HDI + schooling, data = le_df)
summary(stepwise)
```


## Multi-collinearity

```{r}
check_collinearity(no_influ_stepwise)

#remove under_five variable
final_stepwise = lm(le ~ adult_mort + infantdeaths + alcohol + bmi + polio + total_exp + diphtheria + hiv_aids + gdp + thin_1_19 + HDI + schooling, data = no_influ_le)
summary(final_stepwise)
check_collinearity(final_stepwise)

```

## Model Validation

```{r}
set.seed(1)

# Use 5-fold validation and create the training sets
train = trainControl(method = "cv", number = 5)

# Fit the 4-variables model
model = train(le ~ adult_mort + infantdeaths + alcohol + bmi + polio + total_exp + diphtheria + hiv_aids + gdp + thin_1_19 + HDI + schooling, data = no_influ_le, trControl = train, method = 'lm', na.action = na.pass)

model$finalModel
print(model)
```

## normalized RMSE

```{r}
rmse = model$results$RMSE / (max(no_influ_le$le) - min(no_influ_le$le))
rmse
```


## Added variable plot

```{r}
avPlots(final_stepwise)
```

